export const MODULE_NAME = 'map';

export const ACTION_TYPES = {
  AREAS_FETCHED: `${MODULE_NAME}/AREAS_FETCHED`,
  STATISTCS_FETCHED: `${MODULE_NAME}/STATISTCS_FETCHED`,
  INDICATORS_FETCHED: `${MODULE_NAME}/INDICATORS_FETCHED`,
  YEARS_FETCHED: `${MODULE_NAME}/YEARS_FETCHED`,
};
