export const MODULE_NAME = 'map';

export const ACTION_TYPES = {
  AREAS_FETCHED: `${MODULE_NAME}/AREAS_FETCHED`,
  STATISTCS_FETCHED: `${MODULE_NAME}/STATISTCS_FETCHED`,
  INDICATORS_FETCHED: `${MODULE_NAME}/INDICATORS_FETCHED`,
  YEARS_FETCHED: `${MODULE_NAME}/YEARS_FETCHED`,
  AREA_SELECTED: `${MODULE_NAME}/AREA_SELECTED`,
  SET_STATISTICS_WINDOW_VISIBILITY: `${MODULE_NAME}/SET_STATISTICS_WINDOW_VISIBILITY`,
  SET_MAP: `${MODULE_NAME}/SET_MAP`,
  SET_ZOOM: `${MODULE_NAME}/SET_ZOOM`
};
